version: 2

project_name: go-beats

before:
  hooks:
    - go mod tidy

builds:
  - id: go-beats
    main: ./cmd/go-beats
    binary: go-beats
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: go-beats
    formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: rolniuq
    name: go-beats
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
